name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Test in Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm build
      run: |
        npm run build
        npm run test
      env:
        CI: true

    - name: Deploy via SCP
      uses: tanmancan/deploy-action@master
      with:
        user: 'My Test User'
        host: 'My Test Host'
        port: 99
        key: 'My Test Key'
        local_path: 'My Test Local Path'
        remote_path: 'My Test Remote Path'
